---

# https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/install/installRecommendSettings.html


- name: Disable Swappiness
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    sysctl_file: "{{ cassandra_sysctl_file }}"
    reload: yes

- name: Disable SWAP
  shell:
    cmd: |
      swapoff --all
  args:
    executable: /bin/bash
 
- name: Remove SWAP from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Set Recommended Linux Kernel Options
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ cassandra_sysctl_file }}"
    reload: yes
  loop: "{{ cassandra_sysctl_vars }}"
  
- name: Set Resource Limits for cassandra User
  pam_limits:
    domain: cassandra
    dest: "{{ cassandra_limits_file }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 100000 }
    - { limit_type: '-', limit_item: 'nproc', value: 32768 }
    - { limit_type: '-', limit_item: 'memlock', value: unlimited }
    - { limit_type: '-', limit_item: 'as', value: unlimited }
    

- name: Reload Settings From All System Configuration Files
    shell: sysctl --system
      
      
      
      
