---

- name: Configure Main Configuration File configure.yaml
  template:
    src: "{{ cassandra_configuration_template }}"
    dest: "{{ cassandra_configuration_file }}"
    owner: root
    group: root
    mode: 0o644
  notify:
    - cassandra_restart_service
