---

# https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/install/installRecommendSettings.html


- name: 
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    sysctl_file: "{{ cassandra_sysctl_file }}"
    reload: yes

- name: Disable SWAP
  shell:
    cmd: |
      swapoff --all
  args:
    executable: /bin/bash
 
- name: Remove SWAP from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Set Recommended Linux Kernel Options
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ cassandra_sysctl_file }}"
    reload: yes
  loop: "{{ cassandra_sysctl_vars }}"
