- name: Install the Cassandra Package (YUM)
  # Retries are in this as the cache has been seen to still be updating when
  # this task gets to be executed.
  yum:
    name: "{{ cassandra_package }}"
    update_cache: true
  delay: "{{ cassandra_task_delay }}"
  retries: "{{ cassandra_task_retries }}"
  register: cassandra_yum_install_result
  until: cassandra_yum_install_result is succeeded
