---

# https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/configuration/configCassandra_yaml.html#configCassandra_yaml__asterisks

- name: "Install and Configure Cassandra Cluster"

  hosts: all
  
  vars:
    commitlog_directory: "/commitlog/cassandra/commitlog"
    data_file_directories: "/data/cassandra/data"
    hints_directory: "/data/cassandra/hints"
    saved_caches_directory: "/data/cassandra/saved_caches"
      
    cluster_name: columbia_2022
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    num_tokens: 16
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    endpoint_snitch: SimpleSnitch
      
      
      
      
      
    cassandra_directories:
      root:
        group: root
        mode: "0755"
        owner: root
        paths:
          - /data
          - /commitlog
      data:
        paths:
          - /data/cassandra
          - /data/cassandra/data
          - /data/cassandra/hints
          - /data/cassandra/saved_caches
      commitlog:
        paths:
          - /commitlog/cassandra
          - /commitlog/cassandra/commitlog
        

  roles:
    - {role: "cassandra", cassandra__action: "configure_repofile"}
    - {role: "cassandra", cassandra__action: "install_packages"}
    - {role: "cassandra", cassandra__action: "backup_config"}
    - {role: "cassandra", cassandra__action: "create_directories"}
    - {role: "cassandra", cassandra__action: "configure_linux"}
    - {role: "cassandra", cassandra__action: "configure_cluster"}
    - {role: "cassandra", cassandra__action: "service"}    
    

